# Generated by Django 4.2.7 on 2023-11-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_text1_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text1',
            field=models.TextField(),
        ),
    ]
